apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-30m7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-30m7@sha256:cdcfcc2e086956f40ece2e18a799093693d7479d76a3d7864227031e8ff977ad
        name: my-nodejs
        resources: {}
status: {}
